### ISSUE TITLE
[ Feat : Display Selected Images via "Add Image" Btn. in QuillEditor ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#1077]
**Is your feature request related to a problem? Please describe.**
The current functionality of the "Add Image" button in the tutorial, allows users to select files, but the selected image is not being displayed on the QuillEditor as expected.

**Describe the solution you'd like**
Upon selecting an image using the "Add Image" button, the selected image should be displayed within the QuillEditor.

**Describe alternatives you've considered**
An alternative could be to remove the "Add Image" button and rely solely on the QuillEditor for image insertion. However, this alternative might impact the app's design.

**Additional context**
Here's video showing how it works currently :

https://github.com/scorelab/Codelabz/assets/123815256/862758c8-8dac-49a5-a170-55312d2af13e

The desired behavior is for the selected image to be shown in the editor.

**Comment by AnshulKahar2729** [comment]
I think going with removing of "Add Image" button would be better and less confusing for the user. Since the editor in itself has the functionality for adding the images to the editor. Let me know with which direction you want to go. This was my suggestions or sort of opinion, I'm happy to implement either of one
