### ISSUE TITLE
Implement “Connect Social Media” Buttons for Users and Organization

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#453]
**Is your feature request related to a problem? Please describe.**
- Social Media Connections haven't been implemented yet for organizations. 
- Implement "Connect Social Media" actions in both Users and Org 
**(Don't implement the organization settings social media buttons for now)**

- [ ] Implement Connect Social Media for Users Settings

**Describe the solution you'd like**
reference : https://firebase.google.com/docs/auth/web/account-linking

![image](https://user-images.githubusercontent.com/73013838/193538437-cd6aaef1-b49b-41f2-aefb-95d62a262077.png)
![image](https://user-images.githubusercontent.com/73013838/193538453-705c2412-cf81-4268-af7e-50129f130e85.png)

**Comment by akankshat05** [comment]
@Sarfraz-droid I would like to work on this

**Comment by ABHISHEK-PANDEY2** [comment]
@Sarfraz-droid That would be amazing , i would like to contribute to it

**Comment by sulogna2001** [comment]
Hey @Sarfraz-droid  I would like to work on this issue, Please do assign this to me

**Comment by ozair-dev** [comment]
I'm available to work on this issue. Assign it to me

**Comment by Sarfraz-droid** [comment]
@ozair-dev @sulogna2001 Before working on it, do share a brief on the implementation on this issue first

**Comment by ozair-dev** [comment]
Hi Sarfraz, as far as I understand from the [firebase resource](https://firebase.google.com/docs/auth/web/account-linking) you provided, you want the user to be able to link his/her account with multiple Auth providers so the same user can login into his account through different providers(Facebook, twitter, github etc) and this issue is different from the #470, is that correct?

If that is the case, then I wan't to ask where do you this feature to be implemented.

The implementation in the picture you provided has different UI implementation from this project. And I don't want to bother 
working with the UI implementation that much as of now. If you can provide me with the style guide for the impenmation, maybe then I can start working on the issue.
![](https://user-images.githubusercontent.com/73013838/193538453-705c2412-cf81-4268-af7e-50129f130e85.png)

**Comment by Sarfraz-droid** [comment]
@ozair-dev So there are at two places where we need to implement connect social media. First is the user and organization. 

Unfortunately we cannot work on Organization settings right now since the fb page registration and twitter page linking would require a dedicated server to handle callbacks.

In that case we just have to implement the Connect Social Media in **User Settings** page
https://firebase.google.com/docs/auth/web/account-linking
