### ISSUE TITLE
Create a better UI for remove step modal

### ISSUE THREAD

**Issue by ABHISHEK-PANDEY2** [scorelab/Codelabz#895]
Currently, the UI of the modal shown when you delete a step is not according to the design theme.
![image](https://github.com/scorelab/Codelabz/assets/95560057/a9d283eb-6342-4327-9958-d3f7f704939f)

Steps to reproduce this :
1. Go to http://localhost:5173/tutorials 
2.  Create a new tutorial
3.  Add a new step.
4.  Click on Remove step

**Task**-
Create a UI for the modal similar to adding a new step.
![image](https://github.com/scorelab/Codelabz/assets/95560057/2c98525b-6be7-477d-b809-1865ae8540a7)

**Comment by perminder-17** [comment]
Can i work on this issue

**Comment by perminder-17** [comment]
Please assign me

**Comment by Aady7** [comment]
Hii @ABHISHEK-PANDEY2 , if this issue can be assigned to more than one person, I would also like to work on it . Having worked with ui of  add new step modal , this issue seems to be very familiar to me.

**Comment by Pheewww** [comment]
Hey @ABHISHEK-PANDEY2 , i would also like to work on this. Maybe @Aady7 and me can join together on this.

**Comment by Jenil-Dobariya** [comment]
Hello @ABHISHEK-PANDEY2 , I was working on this and resolved it! I am creating a PR for it.

Along with this, I found that the " _ADD IMAGES_ " option can also be modified.
![image](https://github.com/scorelab/Codelabz/assets/118374765/a79d1dfa-f952-40ab-b55d-8731dc7ec508)
If you can suggest me about modification, I would love to do it.

**Comment by SwetanshuSingh** [comment]
Hello @ABHISHEK-PANDEY2 , I would love to work on this issue. Can you assign it to me

**Comment by perminder-17** [comment]
> Hello @ABHISHEK-PANDEY2 , I would love to work on this issue. Can you assign it to me

Issue is already resolved by me.

**Comment by SwetanshuSingh** [comment]
Okay @perminder-17

**Comment by aman-tiwari001** [comment]
Hey Community!
My name is Aman Tiwari and I am currently pursuing my Undergrad from Delhi Technological University (DTU). I am thrilled and excited to start my open source contributions.
My tech stack include MongoDB, ReactJS, NodeJS, ExpressJS (MERN). I have made couple of good fullstack projects on this tech stack.
I am interested in working with likeminded people, experienced developer so that I can learn, grow and make meaningful contribution in open source world.
I would love to hear more about ongoing projects and issues where I can start contributing as a beginner.
Looking forward to being an active member of this fantastic community.
Best regards,
Aman Tiwari
https://github.com/aman-tiwari001 (edited)

**Comment by ShreeBohara** [comment]
Hi @ABHISHEK-PANDEY2 Since there is no progress on this issue, I would like to resolve this issue. Can you please assign it to me?

**Comment by Aady7** [comment]
@ABHISHEK-PANDEY2  I have worked with add step modal and had asked for this issue previously..I request you to kindly assign me the issue if it can be assigned to.

**Comment by vaishnavi192** [comment]
@Aady7 are you still working on it ? can I take it up?

**Comment by Aady7** [comment]
@vaishnavi192 I have raised a pr..but this issue has been declared as stale.

**Comment by vaishnavi192** [comment]
@Aady7 ah yes....so like are you going to raise a PR again or not working on it?

**Comment by Aady7** [comment]
@vaishnavi192 I will raise a pr
